version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    ports:
      - "2181:2181"
    env_file:
      - kafka.env
    networks:
      - mynetwork

  kafka:
    user: root
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
      - "9092:9092"
    env_file:
      - kafka.env
    networks:
      - mynetwork

  postgres:
    image: 'postgres:15'
    container_name: 'postgres'
    ports:
      - "5432:5432"
    env_file:
      - db.env
    networks:
      - mynetwork
    volumes:
      - db-data:/var/lib/postgresql/data

  deal:
    build: ./deal
    container_name: 'deal'
    depends_on:
      - zookeeper
      - kafka
      - postgres
    env_file:
      - app.env
    restart: on-failure
    networks:
      - mynetwork
    ports:
      - "8081:8081"

  calculator:
    build: ./calculator
    container_name: 'calculator'
    depends_on:
      - postgres
      - kafka
      - zookeeper
      - deal
    env_file:
      - app.env
    restart: on-failure
    networks:
      - mynetwork
    ports:
      - "8080:8080"

  statement:
    build: ./statement
    container_name: 'statement'
    depends_on:
      - deal
    env_file:
      - app.env
#    restart: on-failure
    networks:
      - mynetwork
    ports:
      - "8082:8082"

  dossier:
    build: ./dossier
    container_name: 'dossier'
    depends_on:
      - deal
      - zookeeper
      - kafka
    env_file:
      - app.env
    restart: on-failure
    networks:
      - mynetwork
    ports:
      - "8083:8083"

  gateway:
    build: ./gateway
    container_name: 'gateway'
    depends_on:
      - postgres
      - deal
      - calculator
      - statement
      - dossier
      - zookeeper
      - kafka
    env_file:
      - app.env
    restart: on-failure
    networks:
      - mynetwork
    ports:
      - "8888:8888"

networks:
  mynetwork:
    driver: bridge

volumes:
  db-data:
    driver: local