version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    ports:
      - "22181:2181"
    env_file:
      - kafka.env
  kafka:
    user: root
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
      - "9092:9092"
    env_file:
      - kafka.env

  postgres:
    image: 'postges:15'
    container_name: 'postgres'
    ports:
      - "5432:5432"
    env_file:
      - db.env
    networks:
      - mynetwork
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  mynetwork:
    driver: bridge

volumes:
  db-data:
    driver: local